### ISSUE TITLE
Dark variant using light theme

### ISSUE THREAD

**Issue by EllBock** [nrhodes91/AdMin#2]
If some app uses the dark theme variant, the light theme is displayed instead. I'm using OSX slimmest light theme.
The easiest way to replicate this is forcing the dark theme variant of the Terminal app.

Keep up the good work, GNOME should use this theme by default.

**Comment by rhodesn** [comment]
Thanks for the heads up - I'm sure that I've read that the theme 'dark variant' options are being deprecated in favour of a dedicated dark theme (the reason Adwaita theme was split into light/dark), however I can't find the reference.

I've updated the light theme to include a `gtk-dark.css` output which should get this working for you.

You'll have to re-run the `parse-sass.sh` in the light-slimmer theme :smile: 

Thanks!

P.S I don't think it's possible to do the same for the dark theme, Gnome doesn't recognise a `gtk-light.css` for example.

**Comment by EllBock** [comment]
Thank you, really, for the fast response and effort.
I'm sorry to bother you again, but compiling the css returns this error:
```
Internal Error: File to read not found or unreadable: gtk-contained-dark.scss
```

**Comment by rhodesn** [comment]
I'm so sorry that was a total oversight on my part, I missed adding the new gtk-contained-dark.scss file! Just added it so if you wouldn't mind trying again and let me know how you get on!

**Comment by EllBock** [comment]
It is working now! I guess I like my terminal black, but other windows look better in lighter colors. :joy:
I don't know if this feature is deprecated, but I can see some apps still using the dark variant by default, like the Weather app. I'd suggest you add this feature to all light themes at some point.

Thanks again!
