### ISSUE TITLE
Toggle buttons in CSD expand header bar height

### ISSUE THREAD

**Issue by SaucySauce** [nrhodes91/AdMin#4]
I've checked in gnome-tweaks. On any page where toggle buttons aren't found the header bar remains the same height. However, the extensions page does have a toggle button and the header bar increases in height by 4 or 5 pixels.

gnome settings also appears to have the same bug but to a lesser extent.

**Comment by SaucySauce** [comment]
![Screenshot-20190629033649-675x194](https://user-images.githubusercontent.com/38703177/60379250-2c55e080-9a1f-11e9-8368-02f3dab23f6d.png)

**Comment by rhodesn** [comment]
Thanks @SaucySauce. I did notice that but wasn't sure if anyone used the thicker theme. I'll take a look this weekend :+1:

**Comment by rhodesn** [comment]
I've just pushed an update that reduces the size of the sliders in all themes (should have done this a while ago). I'm no longer seeing the headerbar size change when switching between tabs in gnome-tweaks; let me know if it's fixed for you as well.

**Comment by SaucySauce** [comment]
Sorry for the late reply, was fixing the wifi on Fedora 30. The new update fixed the bug. Thank you. Sorry if I'm being picky, I'm a stickler for detail.
