### ISSUE TITLE
Revamp the gnome-shell top bar theme

### ISSUE THREAD

**Issue by SaucySauce** [nrhodes91/AdMin#5]
https://github.com/hrdwrrsk/adementary-theme
Has a great looking gnome-shell/top bar theme. It already follows most of the GNOME design.
Maybe you could tweak yours to be a bit more like it. Just a suggestion.

**Comment by SaucySauce** [comment]
Something between the original Adwaita and Adementary's top bar. Use the latter style and context menus with the former style. Again, just a suggestion. If I knew git and how to do themes I'd do some pull requests in no time.

**Comment by rhodesn** [comment]
Thanks for the suggestion, I won't be making style changes to the gnome-shell theme though. You'll need to run the two as separate themes, one for the shell and one for gtk.
