### ISSUE TITLE
Install theme to /usr/share/themes/ ?

### ISSUE THREAD

**Issue by mld9401** [nrhodes91/AdMin#9]
The installer included in the README.md allows to install the theme into ~/.themes/
I am wondering how to install this theme into system (/usr/share/themes/) to get it works with apps that require root access like (synaptic).

**Comment by rhodesn** [comment]
I'd never thought about that, thanks. You should be able to make path changes to the installation steps to install it to `/usr/share/themes`. Something like the following:

```sh
$ sudo git clone https://github.com/nrhodes91/AdMin /usr/share/themes/AdMin/
$ for theme in /usr/share/themes/AdMin/admin-gtk*; do sudo ln -sf $theme /usr/share/themes/; done
$ sudo find /usr/share/themes/AdMin -type f -name parse-sass.sh -execdir {} \;
```

Let me know if you hit any issues.

**Comment by mld9401** [comment]
> I'd never thought about that, thanks. You should be able to make path changes to the installation steps to install it to `/usr/share/themes`. Something like the following:
> 
> ```shell
> $ sudo git clone https://github.com/nrhodes91/AdMin /usr/share/themes/AdMin/
> $ for theme in /usr/share/themes/AdMin/admin-gtk*; do sudo ln -sf $theme /usr/share/themes/; done
> $ sudo find /usr/share/themes/AdMin -type f -name parse-sass.sh -execdir {} \;
> ```
> 
> Let me know if you hit any issues.

YES, now it works like charm. Thanks a lot
i think now you have to add those instructions to install this theme system-wide 
Thank you.

**Comment by rhodesn** [comment]
I'll definitely see if I can generalise the installation notes to cover user chosen installation paths 👍
